### ISSUE TITLE
Changed the name on images from 'Scooby Doo' to 'Scrappy-Doo'  :)

### ISSUE THREAD

**Issue by terryblue99** [learn-co-curriculum/js-dom-and-events-css-libraries-readme#3]
[CSS Libraries.docx](https://github.com/learn-co-curriculum/js-dom-and-events-css-libraries-readme/files/1668961/CSS.Libraries.docx)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @terryblue99.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
