### ISSUE TITLE
look fancy instead of like fancy

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-dom-and-events-css-libraries-readme#4]
The below sentence should say "look fancy" instead of "like fancy":

"It doesn't make our buttons like fancy or anything like that, but we're not concerned with that right now."

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe the issue is resolved.
