### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by JuanGongora** [learn-co-curriculum/js-dom-and-events-css-libraries-readme#5]
Typo in line 156:

`We don't want to the image to take up more space than it should, so let's add a`

It should instead be:

`We don't want the image to take up more space than it should, so let's add a`

**Comment by drakeltheryuujin** [comment]
Hi @JuanGongora 
Thanks again for spotting this issue.
We have updated the materials and believe your issue to have been resolved.
